@echo off
REM ===========================================================================
REM build.bat - compile the core and emit a BUILD-ID-TAGGED .rbf
REM
REM The released core carries the SAME id the pause panel displays, so you can
REM read the version off the screen and know exactly which file on the SD card
REM is running:
REM     releases\Rbisland_260812_03.rbf   <->   "VERSION RI-260812.03"
REM
REM The id is YYMMDD.NN, where NN counts the builds made that day. It is
REM generated by sys\build_id.tcl, which Quartus runs as PRE_FLOW_SCRIPT_FILE
REM (see Rbisland.qsf) -- so build_id.v is rewritten by the compile itself and
REM must be read AFTER it, never before. Editing build_id.v by hand does
REM nothing; the next compile overwrites it.
REM
REM The '.' becomes '_' in the filename because a second dot in a Windows
REM filename is legal but reads as an extension to some tooling.
REM
REM Because NN increments every compile, builds no longer overwrite each other
REM the way the old date-only name did. Pass an extra suffix to label a build,
REM e.g.  build.bat rot   ->  releases\Rbisland_260812_03rot.rbf
REM
REM Quartus itself always writes output_files\Rbisland.rbf (GENERATE_RBF_FILE
REM is ON in the .qsf); the untagged file is left in place so nothing that
REM references it breaks.
REM ===========================================================================
setlocal

set "QUARTUS=C:\intelFPGA_lite\17.0\quartus\bin64"
set "ROOT=%~dp0"
set "PROJ=Rbisland"
REM "build.bat release" ALSO writes the name the MiSTer wiki requires for an
REM arcade core -- Arcade-<core>_YYYYMMDD.rbf -- which is the only file that
REM should be committed to releases/. Without it you get a dev build only.
REM
REM Two names for one bitstream is deliberate: the wiki name has no per-day
REM sequence, so it cannot identify WHICH build of that day is on the board,
REM and that is exactly what the pause panel is for. The dev name keeps that
REM link; the release name keeps the reviewers happy.
set "SUFFIX=%~1"
set "RELEASE="
if /i "%~1"=="release" (
	set "RELEASE=1"
	set "SUFFIX="
)

if not exist "%QUARTUS%\quartus_sh.exe" (
	echo ERROR: quartus_sh.exe not found at %QUARTUS%
	exit /b 1
)

REM Delete any previous .rbf FIRST. Quartus leaves the old one in place if a
REM compile fails or is interrupted (a crash, a reboot, a killed process), and
REM a stale .rbf that looks like a fresh build is the worst possible outcome --
REM you would flash it, see no change, and conclude the fix did not work.
REM With it deleted up front, the file existing at all proves this run made it.
if exist "%ROOT%output_files\%PROJ%.rbf" del /q "%ROOT%output_files\%PROJ%.rbf"

echo === compiling %PROJ% ===
"%QUARTUS%\quartus_sh.exe" --flow compile "%ROOT%%PROJ%.qpf" -c %PROJ%
if errorlevel 1 (
	echo.
	echo BUILD FAILED - no .rbf produced.
	exit /b 1
)

if not exist "%ROOT%output_files\%PROJ%.rbf" (
	echo.
	echo ERROR: compile reported success but output_files\%PROJ%.rbf is missing.
	echo Check that GENERATE_RBF_FILE is ON in %PROJ%.qsf.
	exit /b 1
)

REM ---------------------------------------------------------------------------
REM Read the id the compile just generated. "260812.03" -> "260812_03".
REM
REM The regex matches the opening quote with '.' rather than an escaped quote:
REM cmd parses the double quotes inside a for /f command BEFORE powershell ever
REM sees them, and an escaped \" unbalances that parse ("was unexpected at this
REM time"). Keep the inner command free of double quotes.
REM ---------------------------------------------------------------------------
set "STAMP="
if exist "%ROOT%build_id.v" (
	for /f "usebackq delims=" %%i in (`powershell -NoProfile -Command "$m=[regex]::Match((Get-Content -Raw '%ROOT%build_id.v'),'BUILD_DATE\s+.([0-9]{6})\.([0-9]{2})'); if($m.Success){$m.Groups[1].Value+'_'+$m.Groups[2].Value}"`) do set "STAMP=%%i"
)

REM Fall back to the date rather than writing "Rbisland_.rbf". A build_id.v
REM that does not parse means the pre-flow script did not run, so warn -- the
REM version on the pause panel will not match this filename.
if not defined STAMP (
	echo.
	echo WARNING: could not read a build id from build_id.v -- falling back to
	echo          the date. The pause panel version will NOT match the filename.
	for /f %%i in ('powershell -NoProfile -Command "Get-Date -Format yyMMdd"') do set "STAMP=%%i"
)

if not exist "%ROOT%releases" mkdir "%ROOT%releases"
copy /y "%ROOT%output_files\%PROJ%.rbf" "%ROOT%releases\%PROJ%_%STAMP%%SUFFIX%.rbf" >nul
if errorlevel 1 exit /b 1

echo.
echo === built releases\%PROJ%_%STAMP%%SUFFIX%.rbf ===
for %%F in ("%ROOT%releases\%PROJ%_%STAMP%%SUFFIX%.rbf") do echo     %%~zF bytes

REM ---------------------------------------------------------------------------
REM Release copy. YYYYMMDD here, not the YYMMDD.NN build id -- the wiki
REM convention is a plain date, and this is the file that gets committed.
REM ---------------------------------------------------------------------------
if defined RELEASE (
	for /f %%i in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd"') do set "RSTAMP=%%i"
	call :emit_release
)
goto :done

:emit_release
copy /y "%ROOT%output_files\%PROJ%.rbf" "%ROOT%releases\Arcade-%PROJ%_%RSTAMP%.rbf" >nul
if errorlevel 1 exit /b 1
echo === release  releases\Arcade-%PROJ%_%RSTAMP%.rbf ===
echo     (commit this one; the dev build above is local only)
goto :eof

:done
endlocal
